name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies for solution
        run: dotnet restore DrawingsIdentifier/DrawingsIdentifier.sln
      - name: Build solution
        run: dotnet build DrawingsIdentifier/DrawingsIdentifier.sln --no-restore

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test solution
        run: dotnet test DrawingsIdentifier/DrawingsIdentifier.sln --no-build --verbosity normal
